module.exports = {

    BEACONS_LOADED : 'BEACONS_LOADED',
    CHANGE_LOCALE : 'CHANGE_LOCALE',
    SHOW_BEACON : 'SHOW_BEACON',
    SHOW_MAIN : 'SHOW_MAIN',
    SHOW_TOP : 'SHOW_TOP',
    SHOW_CYCLING : 'SHOW_CYCLING',
    SHOW_ABOUT : 'SHOW_ABOUT',
    SPEAK_START : 'SPEAK_START',
    SPEAK_END : 'SPEAK_END',
    SHOW_COUPON : 'SHOW_COUPON',
    RESET_COUPON : 'RESET_COUPON',
    APP_RESET : 'APP_RESET',
    SHOW_STATUS : 'SHOW_STATUS',
    SET_PERIPHERAL : 'SET_PERIPHERAL',
    BEACONS_FOUND : 'BEACONS_FOUND',
    CHANGE_BEACON : 'CHANGE_BEACON'

};